export enum StatCategory {
  PTS = 'PTS',
  FGM = 'FGM',
  FGA = 'FGA',
  FG_PCT = 'FG%',
  FG3M = '3PM',
  FG3A = '3PA',
  FG3_PCT = '3P%',
  FTM = 'FTM',
  FTA = 'FTA',
  FT_PCT = 'FT%',
  OREB = 'OREB',
  DREB = 'DREB',
  REB = 'REB',
  AST = 'AST',
  STL = 'STL',
  BLK = 'BLK',
  TOV = 'TOV',
  EFF = 'EFF',
  AST_TOV = 'AST/TO',
  STL_TOV = 'STL/TOV',
  PF = 'PF',
  Default = PTS,
}
